ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;    


SELECT TABLE_NAME as NOMBRETABLA, count(COLUMN_NAME) as NUMCOLUMNAS, count(case when NULLABLE='Y' then 1 end) as NUMCOLUMNASNULL, LAST_ANALYZED as ULTIMOANAlISIS
FROM ALL_TAB_COLUMNS
WHERE table_name IN ('BARES', 'BEBEDORES', 'BEBIDAS', 'FRECUENTAN', 'GUSTAN', 'SIRVEN', 'TIPO_BEBIDA')
group by TABLE_NAME, LAST_ANALYZED
order by TABLE_NAME;
