SELECT op.IDOPERADOR, SUM((TRUNC(res.FECHAFINALRESERVA) - TRUNC(res.FECHAINICIALRESERVA)) *ofer.PRECIOBASE) as DINERO_RECIBIDO
FROM OPERADOR op
JOIN INMUEBLE inm ON op.IDOPERADOR =inm.IDOPERADOR
JOIN OFERTAALOJAMIENTO ofer ON inm.IDINMUEBLE =ofer.INMUEBLEASOCIADO
JOIN RESERVA res ON ofer.IDOFERTA =res.IDOFERTAASOCIADA
WHERE(EXTRACT(YEARFROMres.FECHARESERVA) =:anioActual OR EXTRACT(YEARFROMres.FECHARESERVA) =:anioAnterior)
GROUP BY op.IDOPERADOR
