SELECT o.idOferta, COUNT(*) AS cantidadReservas
FROM OfertaAlojamiento o
JOIN Reserva r ON r.idOfertaAsociada = o.idOferta
WHERE r.fechaInicialReserva BETWEEN TO_DATE('01-01-2022', 'DD-MM-YYYY') AND TO_DATE('28-01-2022', 'DD-MM-YYYY')
GROUP BY o.idOferta
ORDER BY COUNT(*) DESC
FETCH FIRST ROW ONLY;




--Ejemplos con Inserts
INSERT INTO RESERVA(IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION)
VALUES (9,8,'ninguna','05-01-2022','12-01-2022','03-01-2022',null);
COMMIT;
