SET DEFINE OFF
--sgsfgsdfgsdfgsdfgsdfgsdfgsd
CREATE TABLE Habitacion ( IDINMUEBLE NUMBER(38) primary key,
TIPOHABITACION VARCHAR2(26) NOT NULL,
constraint FKHabitacionInmueble foreign key (IDINMUEBLE) references INMUEBLE(IDINMUEBLE));

--drop table habitacion;

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (26, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (27, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (28, ' Privada');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (29, ' Camarote');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (30, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (31, ' Individual');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (32, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (33, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (34, ' Privada');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (35, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (36, ' Individual');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (37, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (38, ' Camarote');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (39, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (40, ' Privada');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (41, ' Individual');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (42, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (43, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (44, ' Camarote');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (45, ' Privada');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (46, ' Individual');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (47, ' Compartida');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (48, ' Doble');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (49, ' Camarote');

INSERT INTO Habitacion (IDINMUEBLE, TIPOHABITACION) 
VALUES (50, ' Privada');

