SET DEFINE OFF
--gsdfgsdfhdsfhdgsdgf
CREATE TABLE EmpresasAlojamiento ( IDOPERADOR NUMBER(38) primary key,
TIPOEMPRESA VARCHAR2(26) NOT NULL,
HORAAPERTURA NUMBER(38) NOT NULL,
HORACIERRE NUMBER(38) NOT NULL,
constraint FKEmpresaAlojamientoOperador foreign key (IDOPERADOR) references Operador(IDOPERADOR));

--drop table empresasalojamiento;

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (26, ' Arrendamiento', 8, 13);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (27, ' Hotel', 2, 19);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (28, ' Hostal', 6, 15);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (29, ' Arrendamiento', 1, 13);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (30, ' Hostal', 3, 18);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (31, ' Hotel', 0, 19);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (32, ' Arrendamiento', 10, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (33, ' Hostal', 7, 17);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (34, ' Arrendamiento', 8, 14);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (35, ' Hotel', 5, 15);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (36, ' Arrendamiento', 0, 13);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (37, ' Hostal', 11, 18);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (38, ' Hotel', 0, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (39, ' Arrendamiento', 9, 14);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (40, ' Arrendamiento', 6, 18);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (41, ' Hostal', 11, 18);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (42, ' Hotel', 0, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (43, ' Arrendamiento', 3, 18);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (44, ' Hotel', 0, 19);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (45, ' Hostal', 10, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (46, ' Arrendamiento', 8, 13);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (47, ' Arrendamiento', 11, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (48, ' Hostal', 0, 16);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (49, ' Hotel', 9, 14);

INSERT INTO EmpresasAlojamiento (IDOPERADOR, TIPOEMPRESA, HORAAPERTURA, HORACIERRE) 
VALUES (50, ' Arrendamiento', 6, 18);

