SET DEFINE OFF
--sdfgsdfhshdfdsfhgsdfgsdgf
CREATE TABLE PersonasNaturales ( IDOPERADOR NUMBER(38),
OFRECEALOJAMIENTOPORDIAS NUMBER(38) NOT NULL,
constraint FKPersonasNaturalesOperador foreign key (IDOPERADOR) references Operador(IDOPERADOR));

--drop table personasnaturales;

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (1, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (2, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (3, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (4, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (5, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (6, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (7, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (8, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (9, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (10, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (11, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (12, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (13, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (14, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (15, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (16, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (17, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (18, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (19, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (20, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (21, 0);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (22, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (23, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (24, 1);

INSERT INTO PersonasNaturales (IDOPERADOR, OFRECEALOJAMIENTOPORDIAS) 
VALUES (25, 1);

