SET DEFINE OFF
--sdfgsedhserhserhwerhwerh
CREATE TABLE ServiciosPorOferta ( IDOFERTAALOJAMIENTO NUMBER(38),
IDSERVICIOOFRECIDO NUMBER(38),
constraint FKServiciosOFERTAOFERTA foreign key (IDOFERTAALOJAMIENTO) references ofertaalojamiento(idoferta),
constraint FKServiciosOFERTAservicio foreign key (IDServicioofrecido) references servicios(idservicio),
constraint PKSERVICIOSOFERTA primary key(IDOFERTAALOJAMIENTO,IDSERVICIOOFRECIDO));

--drop table ServiciosPorOferta;

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (1, 1);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (1, 2);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (2, 3);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (2, 4);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (3, 5);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (3, 6);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (4, 7);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (4, 8);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (5, 9);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (5, 10);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (6, 11);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (6, 12);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (7, 13);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (7, 14);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (8, 15);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (9, 16);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (9, 17);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (10, 18);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (10, 19);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (11, 20);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (11, 21);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (11, 22);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (12, 23);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (12, 24);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (12, 25);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (13, 26);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (13, 1);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (13, 2);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (14, 3);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (14, 4);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (14, 5);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (15, 6);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (15, 7);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (15, 8);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (16, 9);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (16, 10);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (16, 11);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (17, 12);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (17, 13);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (17, 14);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (18, 15);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (18, 16);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (18, 17);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (19, 18);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (19, 19);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (19, 20);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (20, 21);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (20, 22);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (20, 23);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (21, 24);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (21, 25);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (21, 26);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (22, 20);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (22, 1);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (22, 2);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (23, 3);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (24, 4);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (25, 5);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (26, 6);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (27, 7);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (28, 8);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (29, 9);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (30, 10);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (31, 11);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (32, 12);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (33, 13);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (34, 14);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (35, 15);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (36, 16);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (37, 17);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (38, 18);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (39, 19);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (40, 20);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (41, 21);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (42, 22);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (43, 23);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (44, 24);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (45, 25);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (46, 26);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (47, 2);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (48, 7);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (49, 20);

INSERT INTO ServiciosPorOferta (IDOFERTAALOJAMIENTO, IDSERVICIOOFRECIDO) 
VALUES (50, 1);

