SET DEFINE OFF
--sfdgsdfhsejhwesrthwerhwe
CREATE TABLE Reserva ( IDCLIENTEASOCIADO NUMBER(38),
IDOFERTAASOCIADA NUMBER(38),
PROMOCIONESACTIVAS VARCHAR2(128),
FECHAINICIALRESERVA DATE NOT NULL,
FECHAFINALRESERVA DATE NOT NULL,
FECHARESERVA DATE NOT NULL,
FECHACANCELACION DATE,
constraint FKReservaCliente foreign key (IDCLIENTEASOCIADO) references CLIENTE(IDCLIENTE),
constraint FKReservaOferta foreign key (IDOFERTAASOCIADA) references OFERTAALOJAMIENTO(IDOFERTA),
constraint PKReserva primary key (IDCLIENTEASOCIADO,IDOFERTAASOCIADA));

--drop table Reserva;

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (1, 1, 'Primer mes gratis', to_date('08/03/2023', 'DD/MM/YYYY'), to_date('08/06/2023', 'DD/MM/YYYY'), to_date('14/12/2022', 'DD/MM/YYYY'), to_date('09/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (2, 2, 'Descuento del 10% en el arriendo', to_date('11/02/2023', 'DD/MM/YYYY'), to_date('09/06/2023', 'DD/MM/YYYY'), to_date('25/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (3, 3, 'Servicios incluidos en el precio del arriendo', to_date('25/02/2023', 'DD/MM/YYYY'), to_date('07/06/2023', 'DD/MM/YYYY'), to_date('11/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (4, 4, 'Descuento en la mudanza', to_date('26/02/2023', 'DD/MM/YYYY'), to_date('20/05/2023', 'DD/MM/YYYY'), to_date('05/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (5, 5, 'Sin gastos de administración', to_date('05/02/2023', 'DD/MM/YYYY'), to_date('28/05/2023', 'DD/MM/YYYY'), to_date('18/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (6, 6, 'Limpieza semanal incluida en el precio', to_date('23/02/2023', 'DD/MM/YYYY'), to_date('02/06/2023', 'DD/MM/YYYY'), to_date('01/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (7, 7, 'Descuento en la renovación del contrato', to_date('02/03/2023', 'DD/MM/YYYY'), to_date('04/06/2023', 'DD/MM/YYYY'), to_date('21/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (8, 8, 'Mantenimiento gratis por un año', to_date('03/02/2023', 'DD/MM/YYYY'), to_date('27/05/2023', 'DD/MM/YYYY'), to_date('06/12/2022', 'DD/MM/YYYY'), to_date(' 30/04/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (9, 9, 'Incluye todos los electrodomésticos', to_date('06/03/2023', 'DD/MM/YYYY'), to_date('14/06/2023', 'DD/MM/YYYY'), to_date('27/11/2022', 'DD/MM/YYYY'), to_date(' 17/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (10, 10, ' Descuento en la garantía', to_date(' 07/02/2023', 'DD/MM/YYYY'), to_date(' 06/06/2023', 'DD/MM/YYYY'), to_date(' 08/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (11, 11, ' Estacionamiento gratuito por un mes', to_date(' 28/02/2023', 'DD/MM/YYYY'), to_date(' 03/06/2023', 'DD/MM/YYYY'), to_date(' 12/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (12, 12, ' Primeros 2 meses al 50% de descuento', to_date(' 09/03/2023', 'DD/MM/YYYY'), to_date(' 19/06/2023', 'DD/MM/YYYY'), to_date(' 26/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (13, 13, ' Descuento en la mudanza con nuestro servicio de fletes', to_date(' 03/03/2023', 'DD/MM/YYYY'), to_date(' 16/06/2023', 'DD/MM/YYYY'), to_date(' 09/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (14, 14, ' Incluye servicio de internet', to_date(' 01/03/2023', 'DD/MM/YYYY'), to_date(' 23/05/2023', 'DD/MM/YYYY'), to_date(' 22/11/2022', 'DD/MM/YYYY'), to_date('16/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (15, 15, ' Sin aumento en el precio del arriendo por 2 años', to_date(' 18/02/2023', 'DD/MM/YYYY'), to_date(' 29/05/2023', 'DD/MM/YYYY'), to_date(' 03/12/2022', 'DD/MM/YYYY'), to_date('10/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (16, 16, ' Mes adicional de arriendo gratis por renovación anticipada', to_date(' 22/02/2023', 'DD/MM/YYYY'), to_date(' 22/05/2023', 'DD/MM/YYYY'), to_date(' 24/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (17, 17, ' Descuento en el precio de la luz y el gas', to_date(' 04/03/2023', 'DD/MM/YYYY'), to_date(' 05/06/2023', 'DD/MM/YYYY'), to_date(' 20/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (18, 18, ' Decoración gratis para la sala de estar', to_date(' 17/02/2023', 'DD/MM/YYYY'), to_date(' 17/05/2023', 'DD/MM/YYYY'), to_date(' 01/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (19, 19, ' Limpieza profunda gratis antes de la mudanza', to_date(' 24/02/2023', 'DD/MM/YYYY'), to_date(' 18/05/2023', 'DD/MM/YYYY'), to_date(' 10/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (20, 20, ' Descuento para estudiantes', to_date(' 20/02/2023', 'DD/MM/YYYY'), to_date(' 12/06/2023', 'DD/MM/YYYY'), to_date(' 23/11/2022', 'DD/MM/YYYY'), to_date(' 06/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (21, 21, ' Mes adicional gratis por recomendación de un amigo', to_date(' 12/02/2023', 'DD/MM/YYYY'), to_date(' 11/05/2023', 'DD/MM/YYYY'), to_date(' 17/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (22, 22, ' Incluye servicio de televisión por cable', to_date(' 13/03/2023', 'DD/MM/YYYY'), to_date(' 30/05/2023', 'DD/MM/YYYY'), to_date(' 07/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (23, 23, ' Descuento en el primer mes de arriendo', to_date(' 26/02/2023', 'DD/MM/YYYY'), to_date(' 31/05/2023', 'DD/MM/YYYY'), to_date(' 04/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (24, 24, ' Servicio de mantenimiento 24 horas incluido', to_date(' 27/02/2023', 'DD/MM/YYYY'), to_date(' 13/05/2023', 'DD/MM/YYYY'), to_date(' 15/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (25, 25, ' Descuento en la mudanza con nuestro servicio de mudanzas asociado', to_date(' 10/02/2023', 'DD/MM/YYYY'), to_date(' 25/05/2023', 'DD/MM/YYYY'), to_date(' 29/11/2022', 'DD/MM/YYYY'), to_date(' 20/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (26, 26, ' 2 meses de arriendo gratis por renovación anticipada de 2 años', to_date(' 01/02/2023', 'DD/MM/YYYY'), to_date(' 10/06/2023', 'DD/MM/YYYY'), to_date(' 30/11/2022', 'DD/MM/YYYY'), to_date(' 13/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (27, 27, ' Descuento en la garantía por renovación anticipada', to_date(' 16/02/2023', 'DD/MM/YYYY'), to_date(' 15/06/2023', 'DD/MM/YYYY'), to_date(' 28/11/2022', 'DD/MM/YYYY'), to_date(' 16/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (28, 28, ' Incluye servicio de agua', to_date(' 22/03/2023', 'DD/MM/YYYY'), to_date(' 21/06/2023', 'DD/MM/YYYY'), to_date(' 19/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (29, 29, ' Sin gastos de transferencia', to_date(' 06/02/2023', 'DD/MM/YYYY'), to_date(' 01/06/2023', 'DD/MM/YYYY'), to_date(' 13/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (30, 30, ' Descuento en el arriendo por pago adelantado', to_date(' 19/02/2023', 'DD/MM/YYYY'), to_date(' 08/06/2023', 'DD/MM/YYYY'), to_date(' 16/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (31, 31, ' Servicio de jardinería incluido', to_date(' 05/03/2023', 'DD/MM/YYYY'), to_date(' 26/05/2023', 'DD/MM/YYYY'), to_date(' 02/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (32, 32, ' Mes adicional de arriendo gratis por renovación de 1 año', to_date(' 27/03/2023', 'DD/MM/YYYY'), to_date(' 22/06/2023', 'DD/MM/YYYY'), to_date(' 08/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (33, 33, ' Descuento en la renta por firmar contrato por 2 años', to_date(' 21/02/2023', 'DD/MM/YYYY'), to_date(' 30/05/2023', 'DD/MM/YYYY'), to_date(' 05/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (34, 34, ' Incluye servicio de seguridad', to_date(' 12/03/2023', 'DD/MM/YYYY'), to_date(' 05/05/2023', 'DD/MM/YYYY'), to_date(' 23/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (35, 35, ' Servicio de limpieza de ventanas gratis una vez al mes', to_date(' 13/02/2023', 'DD/MM/YYYY'), to_date(' 24/06/2023', 'DD/MM/YYYY'), to_date(' 04/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (36, 36, ' Descuento en la mudanza con nuestro servicio de transporte asociado', to_date(' 23/03/2023', 'DD/MM/YYYY'), to_date(' 04/05/2023', 'DD/MM/YYYY'), to_date(' 27/12/2022', 'DD/MM/YYYY'), to_date(' 04/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (37, 37, ' Incluye servicio de gas', to_date(' 28/03/2023', 'DD/MM/YYYY'), to_date(' 31/05/2023', 'DD/MM/YYYY'), to_date(' 07/11/2022', 'DD/MM/YYYY'), to_date(' 30/04/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (38, 38, ' Descuento en la renta por pago adelantado de 6 meses', to_date(' 25/02/2023', 'DD/MM/YYYY'), to_date(' 07/06/2023', 'DD/MM/YYYY'), to_date(' 19/12/2022', 'DD/MM/YYYY'), to_date(' 09/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (39, 39, ' Sin gastos de notaría', to_date(' 04/02/2023', 'DD/MM/YYYY'), to_date(' 09/05/2023', 'DD/MM/YYYY'), to_date(' 14/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (40, 40, ' Servicio de reparaciones y mantenimiento incluido', to_date(' 14/03/2023', 'DD/MM/YYYY'), to_date(' 20/06/2023', 'DD/MM/YYYY'), to_date(' 30/11/2022', 'DD/MM/YYYY'), to_date(' 07/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (41, 41, ' Mes adicional de arriendo gratis por referir a un amigo', to_date(' 07/03/2023', 'DD/MM/YYYY'), to_date(' 14/05/2023', 'DD/MM/YYYY'), to_date(' 03/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (42, 42, ' Descuento en la renta por firmar contrato por 3 años', to_date(' 09/02/2023', 'DD/MM/YYYY'), to_date(' 02/06/2023', 'DD/MM/YYYY'), to_date(' 25/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (43, 43, ' Incluye servicio de electricidad', to_date(' 08/02/2023', 'DD/MM/YYYY'), to_date(' 25/06/2023', 'DD/MM/YYYY'), to_date(' 10/12/2022', 'DD/MM/YYYY'), to_date(' 27/05/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (44, 44, ' Descuento en la mudanza con nuestro servicio de embalaje asociado', to_date(' 18/03/2023', 'DD/MM/YYYY'), to_date(' 07/05/2023', 'DD/MM/YYYY'), to_date(' 28/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (45, 45, ' 2 meses de arriendo gratis por renovación anticipada de 3 años', to_date(' 15/02/2023', 'DD/MM/YYYY'), to_date(' 08/05/2023', 'DD/MM/YYYY'), to_date(' 22/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (46, 46, ' Descuento en la garantía por renovación anticipada de 2 años', to_date(' 11/03/2023', 'DD/MM/YYYY'), to_date(' 03/06/2023', 'DD/MM/YYYY'), to_date(' 01/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (47, 47, ' Incluye servicio de limpieza', to_date(' 26/03/2023', 'DD/MM/YYYY'), to_date(' 15/05/2023', 'DD/MM/YYYY'), to_date(' 06/11/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (48, 48, ' Descuento en la renta por pago adelantado de 12 meses', to_date(' 24/03/2023', 'DD/MM/YYYY'), to_date(' 18/06/2023', 'DD/MM/YYYY'), to_date(' 16/12/2022', 'DD/MM/YYYY'), NULL);

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (49, 49, ' Sin gastos de registro', to_date(' 21/03/2023', 'DD/MM/YYYY'), to_date(' 16/05/2023', 'DD/MM/YYYY'), to_date(' 12/12/2022', 'DD/MM/YYYY'), to_date(' 11/06/2023', 'DD/MM/YYYY'));

INSERT INTO Reserva (IDCLIENTEASOCIADO, IDOFERTAASOCIADA, PROMOCIONESACTIVAS, FECHAINICIALRESERVA, FECHAFINALRESERVA, FECHARESERVA, FECHACANCELACION) 
VALUES (50, 50, ' Servicio de conserjería incluido.', to_date(' 16/03/2023', 'DD/MM/YYYY'), to_date(' 26/06/2023', 'DD/MM/YYYY'), to_date(' 20/12/2022', 'DD/MM/YYYY'), to_date(' 18/04/2023', 'DD/MM/YYYY'));

