SET DEFINE OFF
--gssfdgsdfgsdfhgsdhfsewehrwerhwehr
CREATE TABLE Vivienda ( IDINMUEBLE NUMBER(38) primary key,
TIPOVIVIENDA VARCHAR2(128) NOT NULL,
NUMEROHABITACIONES NUMBER(38) NOT NULL,
constraint FKViviendaInmueble foreign key (IDINMUEBLE) references INMUEBLE(IDINMUEBLE));

--drop table vivienda;

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (1, 'Casa', 2);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (2, 'Apartamento', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (3, 'Duplex', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (4, 'Penthouse', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (5, 'Apartaestudio', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (6, 'Loft', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (7, 'Chalet', 4);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (8, 'Mansión', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (9, 'Bungalow', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (10, ' Cabaña', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (11, ' Estudio', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (12, ' Ático', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (13, ' Casa de campo', 4);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (14, ' Casa de ciudad', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (15, ' Casa adosada', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (16, ' Casa de lujo', 4);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (17, ' Departamento', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (18, ' Casa prefabricada', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (19, ' Casa móvil', 2);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (20, ' Chalé adosado', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (21, ' Piso compartido', 2);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (22, ' Habitación en casa compartida', 2);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (23, ' Casa rural', 3);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (24, ' Casa de playa', 1);

INSERT INTO Vivienda (IDINMUEBLE, TIPOVIVIENDA, NUMEROHABITACIONES) 
VALUES (25, ' Casa en la montaña', 3);

