SET DEFINE OFF

CREATE TABLE Cliente ( IDCLIENTE NUMBER(38) primary key ,
VINCULOCONUNIANDES VARCHAR2(26) NOT NULL,
USUARIO VARCHAR2(26) NOT NULL,
CLAVE VARCHAR2(26) NOT NULL);

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (1, 'Estudiante', 'jhonsmith1', 'M1jK!a5p#');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (2, 'Profesor', 'mikerodriguez2', 'R8#vLp4S');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (3, 'Estudiante', 'lisajohnson3', 'D9$zQb2x@');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (4, 'Estudiante', 'jasonbrown4', 'P6^wHc7N');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (5, 'Profesor', 'sarahdavis5', 'G2@kZd9V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (6, 'Estudiante', 'kevinjackson6', 'F5!jKp7W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (7, 'Profesor', 'andrewtaylor7', 'L1%hTc9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (8, 'Estudiante', 'lauramartinez8', 'S6$pGm3B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (9, 'Profesor', 'samuelhernandez9', 'R9^vNl2M');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (10, ' Estudiante', 'annawilson10', 'H3#qFb8Z');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (11, ' Estudiante', 'richardlee11', 'T5!dLj2X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (12, ' Profesor', 'stephanieturner12', 'A2%wKg6S');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (13, ' Profesor', 'davidwhite13', 'C7@zNp4V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (14, ' Estudiante', 'melissasanchez14', 'B4^mHc9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (15, ' Estudiante', 'edwardperez15', 'P8#tQl1W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (16, ' Profesor', 'katiehill16', 'N9!sJk4M');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (17, ' Estudiante', 'jonathanrobinson17', 'D5@fGp7X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (18, ' Profesor', 'victoriagarcia18', 'E7^rLh2B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (19, ' Estudiante', 'jessicarivera19', 'K4#tNj6Z');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (20, ' Profesor', 'danielparker20', 'S3%qCm9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (21, ' Estudiante', 'amandasmith21', 'W1@eKl5V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (22, ' Estudiante', 'christophermartin22', 'F6!zRp7N');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (23, ' Profesor', 'rebecacruz23', 'L8$pTc3X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (24, ' Estudiante', 'jacoblopez24', 'Y7^hJm2B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (25, ' Estudiante', 'oliviahall25', 'G3#fQk6W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (26, ' Profesor', 'matthewyoung26', 'J2%rLp9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (27, ' Estudiante', 'ashleyallen27', 'U4@tNc8V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (28, ' Profesor', 'josephrodriguez28', 'R6^wHj1M');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (29, ' Estudiante', 'emilycampbell29', 'B9!sFm5X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (30, ' Estudiante', 'williammiller30', 'V7#dKl3N');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (31, ' Profesor', 'jessicabaker31', 'C4@zQp8W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (32, ' Estudiante', 'nathanwright32', 'X2^mGk9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (33, ' Profesor', 'kellyclark33', 'M8#tNc5B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (34, ' Estudiante', 'ryanperez34', 'A5%wJp6V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (35, ' Estudiante', 'elizabethscott35', 'N1!sTj9X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (36, ' Profesor', 'alexanderturner36', 'E3^rLm7N');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (37, ' Estudiante', 'caitlinrobinson37', 'S7#fHk2X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (38, ' Profesor', 'jaredgonzalez38', 'K9%qCp4W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (39, ' Estudiante', 'kristensanchez39', 'H5@eGc6B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (40, ' Profesor', 'brianroberts40', 'Z3^wLj7X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (41, ' Estudiante', 'tiffanyjohnson41', 'T1#vNl9M');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (42, ' Estudiante', 'miguelsmith42', 'F7!sKm2X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (43, ' Profesor', 'laurenmartinez43', 'B8$pTc4V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (44, ' Estudiante', 'justinlee44', 'G6^hJk3W');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (45, ' Profesor', 'hannahrodriguez45', 'P4#fQp5N');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (46, ' Estudiante', 'jacobmartin46', 'W2%zGm7X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (47, ' Profesor', 'vanessawilliams47', 'D7@tNc1B');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (48, ' Estudiante', 'sebastianlopez48', 'C5^wHj3V');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (49, ' Estudiante', 'cynthiagarcia49', 'R2!sFp6X');

INSERT INTO Cliente (IDCLIENTE, VINCULOCONUNIANDES, USUARIO, CLAVE)
VALUES (50, ' Profesor', 'ericadavis50', 'L9#dKl4M');

